### PR TITLE
Auto committing

### PR DESCRIPTION
**Pull request by cgalarza**

### CODE REVIEW

**Review by elohanlon — COMMENTED** [review]
This feature is good, but I still don't like the phrasing "auto_commit" on the app side because it sounds like when auto_commit is false, that a URI Service save operation won't automatically commit without an explicit commit call from the client...but it will.

Can we call this "commit_after_save" and only invoke a commit method call when that's true?

**Comment by cgalarza** [comment]
I think either way we run into the wording problem. Because setting `commit_after_save` to false will sound like the results are never going to be committed but that's not true. That's why I added the long description in the readme. If you think `commit_after_save` is clearer, then I am happy to change it.

**Comment by elohanlon** [comment]
If you're okay with `commit_after_save`, I'd prefer it.  Since it's a config option for the rails app, I see it as a clear indication that the app is choosing to commit after save or not.  Then it's up to the URI Service implementer to decide whether the backing Solr instance should autocommit or not.  Imagine if we were using ElasticSearch as the backend instead of Solr.  I'm not sure whether the same notion of autocommit exists there, but I feel like that's a search server concern rather than a rails app concern, so that's why I prefer that the config option applies to the app behavior.

**Comment by elohanlon** [comment]
If you're okay with `commit_after_save`, I'd prefer it.  Since it's a config option for the rails app, I see it as a clear indication that the app is choosing to commit after save or not.  Then it's up to the URI Service implementer to decide whether the backing Solr instance should autocommit or not.  Imagine if we were using ElasticSearch as the backend instead of Solr.  I'm not sure whether the same notion of autocommit exists there, but I feel like that's a search server concern rather than a rails app concern, so that's why I prefer that the config option applies to the app behavior.

**Comment by elohanlon** [comment]
(Did not mean to close this PR.  Just re-opened.)

**Comment by cgalarza** [comment]
Okay, I've change the name of the config key.

**Comment by elohanlon** [comment]
Thank you for the change.  PR looks great.  Approving now!

**Review by elohanlon — APPROVED** [review]

**Pull request merged**
